(function(){
'use strict';
const C=MemoryCore,S=Story,app=document.querySelector('#app');
let state=C.fresh(),storageOK=true,viewResult=false,activeScene=false,sceneTimer=null,sceneFrame=null,selected=null,feedback=null,imageReady=false;
const sceneImage=new Image();sceneImage.src='assets/scene.png?v=20260917-3';sceneImage.decode().then(()=>{imageReady=true;}).catch(()=>{});
try{const raw=localStorage.getItem(C.KEY);if(!raw&&localStorage.getItem('memory417.chapter.v1')){state=C.fresh(true);warn('画面与章节顺序已更新，将从开头开始一份新版记录。');save();}if(raw){const parsed=JSON.parse(raw);if(C.valid(parsed))state=parsed;else warn('旧记录格式无法读取，已开始一份新记录。');}}catch(e){warn('无法读取本机记录。本次仍可游玩，但刷新后可能无法恢复。');}
if(state.scene.started&&!state.scene.finished){state.scene.finished=true;state.scene.interrupted=true;save();}
function warn(text){const e=document.querySelector('#storage-warning');e.textContent=text;e.hidden=false;}
function save(){try{localStorage.setItem(C.KEY,JSON.stringify(state));document.querySelector('#save-status').textContent='已保存在此设备';return true;}catch(e){storageOK=false;document.querySelector('#save-status').textContent='仅本次有效';warn('浏览器未能保存记录。本次仍可游玩；请勿刷新或关闭，结束时可下载记录。');return false;}}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function add(parent,tag,cls,text){const n=el(tag,cls,text);parent.append(n);return n;}
function button(parent,label,fn,cls='primary'){const b=add(parent,'button',cls,label);b.type='button';b.addEventListener('click',fn);return b;}
function paragraphs(parent,lines,cls){lines.forEach(t=>add(parent,'p',cls,t));}
function continueButton(parent,label){const a=add(parent,'div','actions');button(a,label+'  →',next);}
function base(p,narrow=false){const wrap=add(app,'section','sheet'+(narrow?' narrow':''));add(wrap,'div','eyebrow',state.page<8?'现场记录 / 4:17':'调查档案 / 4:17');add(wrap,'h1','',p.title);return wrap;}
function next(){viewResult=false;state.page=Math.min(16,state.page+1);selected=null;feedback=null;save();render();}
function updateChrome(){document.body.classList.toggle('exposure-mode',activeScene);document.querySelector('#page-count').textContent=String(state.page+1).padStart(2,'0')+' / 17';document.querySelector('#progress-fill').style.width=((state.page+1)/17*100)+'%';document.querySelector('#chapter-label').textContent=state.page<8?'现场 · 4:17':state.page<14?'证据 · 比较':'回望 · 调查结束';document.title=state.page>=14?'记忆里多出来的那把伞':'4:17｜二楼走廊';}
function render(){app.replaceChildren();updateChrome();const p=S.pages[state.page];if(viewResult){scorePage();return;}const qi=S.questions.findIndex(q=>q.page===state.page);if(qi>=0){questionPage(qi);finishRender();return;}
switch(state.page){case 0:opening(p);break;case 1:witness(p);break;case 2:firstPage(p);break;case 4:xiaolin(p);break;case 5:leadingPage(p);break;case 6:detailsPage(p);break;case 7:secondPage(p);break;case 8:revealPage(p);break;case 13:conceptPage(p);break;case 14:twistPage(p);break;case 15:scorePage();break;case 16:reflectionPage(p);break;}finishRender();}
function finishRender(){window.scrollTo(0,0);if(!activeScene)app.focus({preventScroll:true});}
function opening(p){const hero=add(app,'section','hero');const img=add(hero,'img','hero-art');img.src='assets/corridor.png';img.alt='黄昏阳光下的长走廊，一扇半开的教室门。';const copy=add(hero,'div','hero-copy');add(copy,'div','eyebrow','教学楼 · 二楼 / 放学后');const h=add(copy,'h1','time');add(h,'small','','下午');h.append('4:17');paragraphs(copy,p.text);add(copy,'div','impact','砰——');add(copy,'p','after-sound',p.end);button(copy,p.button+'  →',next);add(copy,'p','rule-note','下一幕只出现五秒；请准备好，保持页面可见。');const foot=add(app,'div','hero-foot');add(foot,'span','','约 5—10 分钟');add(foot,'span','','17 幕 · 5 次判断');add(foot,'span','','阅读速度不计分');if(state.replay)add(foot,'span','','重玩记录');}
function witness(p){if(state.scene.started){closedScene(p);return;}const wrap=add(app,'section','loading');add(wrap,'h1','','你只有几秒钟。');const status=add(wrap,'p','muted','正在准备画面……');const launch=()=>{if(state.page!==1||state.scene.started)return;if(document.hidden){status.textContent='请回到此页面，再开始观看。';button(wrap,'开始观看',launch);return;}startScene();};if(imageReady)launch();else sceneImage.decode().then(()=>{imageReady=true;launch();}).catch(()=>{status.textContent='画面没有载入，计时尚未开始。请检查素材后重试。';button(wrap,'重新载入画面',()=>{sceneImage.src='assets/scene.png?v=20260917-3';render();});});}
function startScene(){state.scene={started:true,finished:false,interrupted:false,startedAt:Date.now(),endedAt:null};save();activeScene=true;app.replaceChildren();updateChrome();const wrap=add(app,'section','exposure');const top=add(wrap,'div','scene-head');add(top,'span','','4:17 · 教室门口');add(top,'span','','你朝里面看了一眼');const frame=add(wrap,'div','scene-wrap');const img=add(frame,'img');img.src=sceneImage.src;img.alt='从教室门口短暂看到的现场。';img.draggable=false;add(frame,'div','timer-track');window.scrollTo(0,0);const start=performance.now();state.scene.startedAt=Date.now();state.scene.deadline=state.scene.startedAt+5000;save();const tick=()=>{if(!activeScene)return;if(performance.now()-start>=5000){closeScene(false);return;}sceneFrame=requestAnimationFrame(tick);};sceneFrame=requestAnimationFrame(tick);sceneTimer=setTimeout(()=>closeScene(false),5000);}
function closeScene(interrupted){if(!activeScene)return;activeScene=false;clearTimeout(sceneTimer);cancelAnimationFrame(sceneFrame);state.scene.finished=true;state.scene.interrupted=interrupted;state.scene.endedAt=Date.now();save();render();}
function closedScene(p){const wrap=add(app,'section','blackout');add(wrap,'div','empty-time','4:17');paragraphs(wrap,p.text);if(state.scene.interrupted)add(wrap,'p','small','观看曾中断，这次画面已封存。请按实际看到的内容记录。');button(wrap,'继续  →',next);}
function field(parent,label,placeholder,value,oninput){const l=add(parent,'label','field');add(l,'span','',label);const t=add(l,'textarea');t.placeholder=placeholder;t.maxLength=2000;t.value=value||'';t.addEventListener('input',()=>oninput(t.value));return t;}
function firstPage(p){const wrap=base(p,true);paragraphs(wrap,p.text,'intro');if(state.first){add(wrap,'div','sealed','已记录 · 暂不判断对错');continueButton(wrap,'继续');return;}
if(!state.freeLocked){field(wrap,'先用自己的话写下来（可留空）','你记得什么？不必猜测没有把握的细节。',state.freeDraft,v=>{state.freeDraft=v;save();});button(wrap,'保存描述，继续记录',()=>{state.freeLocked=true;save();render();});add(wrap,'p','rule-note','下一步可以补充选择。保存后，这段最初描述将封存。');return;}
add(wrap,'div','sealed','最初描述已封存');add(wrap,'p','','请选择你记得出现过的东西。可以只选「我记不清了」。');const form=add(wrap,'form');const choices=add(form,'div','choices multi');S.firstOptions.forEach((t,i)=>{const l=add(choices,'label','choice');const input=add(l,'input');input.type='checkbox';input.name='first';input.value=t;input.checked=state.firstDraft.includes(t);add(l,'span','',t);input.addEventListener('change',()=>{let chosen=[...choices.querySelectorAll('input:checked')].map(i=>i.value);if(t==='我记不清了'&&input.checked)chosen=[t];else if(input.checked)chosen=chosen.filter(x=>x!=='我记不清了');state.firstDraft=chosen;save();choices.querySelectorAll('input').forEach(i=>i.checked=chosen.includes(i.value));});});field(form,'其他细节（选填）','如果选了其他，可以写在这里。',state.otherDraft,v=>{state.otherDraft=v;save();});const msg=add(form,'p','notice');const b=add(form,'button','primary',p.button);b.type='submit';form.addEventListener('submit',e=>{e.preventDefault();if(!state.firstDraft.length){msg.textContent='请选择至少一项，或选择「我记不清了」。';return;}state.first={text:state.freeDraft,items:[...state.firstDraft],other:state.otherDraft,at:new Date().toISOString()};save();render();});}
function questionPage(index){const q=S.questions[index],record=state.questions[index];const wrap=add(app,'section','sheet');add(wrap,'span','question-number',String(index+1).padStart(2,'0'));const kick=add(wrap,'div','question-kicker');add(kick,'span','','正式判断 '+(index+1)+' / 5');add(kick,'span','',q.title);add(wrap,'p','intro',q.intro);add(wrap,'h1','question-prompt',q.prompt);const form=add(wrap,'form');const options=add(form,'div','choices');q.options.forEach((t,i)=>{const l=add(options,'label','choice');const input=add(l,'input');input.type='radio';input.name='answer';input.value=i;input.disabled=record.solved;input.checked=record.solved?i===q.correct:selected===i;add(l,'span','letter','ABCD'[i]);add(l,'span','',t);input.addEventListener('change',()=>selected=i);});if(record.hint)add(form,'div','hint-box','提示 · '+q.hint);
const current=record.solved?q.correct:feedback;
if(current!==null){const fb=add(form,'div','feedback'+(record.solved?' correct':''));fb.setAttribute('role','status');add(fb,'strong','',record.solved?'判断已完成':'再想一步');add(fb,'span','',q.feedback[current]);}
const a=add(form,'div','actions');if(record.solved){button(a,'继续  →',next);add(form,'p','rule-note','本题 '+record.points+' 分 · '+(record.hint?'借助提示掌握':record.points===100?'首次独立答对':'纠错后掌握'));}else{const submit=add(a,'button','primary',feedback!==null?'重新提交':'提交判断');submit.type='submit';button(a,record.hint?'已使用提示':'需要一点提示？',()=>{state.questions[index]=C.hint(record);save();render();},'quiet').disabled=record.hint;add(form,'p','rule-note','首次独立答对 100% · 纠错后 60% · 使用提示后 30%。均需答对才可继续。');form.addEventListener('submit',e=>{e.preventDefault();if(selected===null){const n=add(form,'p','notice','请先选择一个答案。');n.setAttribute('role','alert');return;}state.questions[index]=C.answer(record,selected,q.correct);feedback=selected;save();render();});}}
function xiaolin(p){const wrap=add(app,'section','split');const img=add(wrap,'img','portrait');img.src='assets/xiaolin.png';img.alt='同学小林站在黄昏的走廊里，向你讲述他的印象。';const copy=add(wrap,'div','dialogue');add(copy,'div','eyebrow',p.eyebrow);add(copy,'h1','',p.title);paragraphs(copy,p.text,'quote');add(copy,'p','muted',p.end);continueButton(copy,p.button);}
function radioGroup(parent,legend,choices,name){const fs=add(parent,'fieldset');add(fs,'legend','',legend);choices.forEach((v,i)=>{const l=add(fs,'label','choice');const input=add(l,'input');input.type='radio';input.name=name;input.value=v;input.required=true;add(l,'span','',v);});}
function leadingPage(p){const wrap=base(p,true);paragraphs(wrap,p.text,'intro');if(state.leading){add(wrap,'div','sealed','已记下你的回答');continueButton(wrap,'继续');return;}const form=add(wrap,'form');radioGroup(form,'按你现在的印象选择',S.leadingOptions,'leading');add(form,'p','notice','本项不计分。');add(form,'button','primary',p.button).type='submit';form.addEventListener('submit',e=>{e.preventDefault();state.leading={answer:new FormData(form).get('leading'),at:new Date().toISOString()};save();render();});}
function detailsPage(p){const wrap=base(p,true);paragraphs(wrap,p.text,'intro');if(state.details){add(wrap,'div','sealed','已记录');continueButton(wrap,'继续');return;}const form=add(wrap,'form');const groups=add(form,'div','detail-fields');radioGroup(groups,'地上的笔记本是什么颜色？',['红色','蓝色','黑色','记不清'],'notebook');radioGroup(groups,'那瓶水放在哪里？',['桌面上','地上','椅面上','我没注意'],'water');const a=add(form,'div','actions');add(a,'button','primary',p.button).type='submit';form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);state.details={notebook:fd.get('notebook'),water:fd.get('water')};save();render();});}
function secondPage(p){const wrap=base(p,true);if(state.second){add(wrap,'div','sealed','这次回答已封存');add(wrap,'p','text-lead','你确定——');add(wrap,'p','text-lead','这是你「看见」的？');add(wrap,'p','text-lead','还是后来「听见」的？');continueButton(wrap,'查看原始记录');return;}paragraphs(wrap,p.text,'intro');const form=add(wrap,'form');const options=add(form,'div','choices');S.memoryOptions.forEach((v,i)=>{const l=add(options,'label','choice');const input=add(l,'input');input.type='radio';input.name='second';input.value=i;input.required=true;add(l,'span','',v);});add(form,'p','notice','按你的印象填写，本项不计分。');add(form,'button','primary',p.button).type='submit';form.addEventListener('submit',e=>{e.preventDefault();state.second={choice:Number(new FormData(form).get('second')),at:new Date().toISOString()};save();render();});}
function revealPage(p){const wrap=add(app,'section');const heading=add(wrap,'div','replay-title');add(heading,'h1','',p.title);add(heading,'p','muted','原始画面 · 同一素材 · 不限时');const grid=add(wrap,'div','reveal-layout');const left=add(grid,'div');const frame=add(left,'div','scene-wrap evidence-panel');const img=add(frame,'img');img.src='assets/scene.png?v=20260917-3';img.alt='教室原图：倒下的椅子、红色笔记本、蓝色书包、桌上透明水瓶，以及正在离开的学生。画面没有雨伞。';const spot=add(frame,'div','hotspot');spot.hidden=true;const controls=add(left,'div','evidence-buttons');const boxes=[[33,50,31,34],[29,79,15,11],[5,55,22,22],[92,29,5,16],[84,22,7,22]];['倒下的椅子','红色笔记本','蓝色书包','透明水瓶','离开的学生'].forEach((t,i)=>{const b=button(controls,'✓ '+t,()=>{controls.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');const [x,y,w,h]=boxes[i];spot.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;spot.hidden=false;},'');b.setAttribute('aria-pressed','false');});button(controls,'完整画面',()=>{spot.hidden=true;controls.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));},'');add(left,'p','rule-note','这是这段故事使用的原始插画，不是新找到的监控录像。');
const box=add(grid,'aside','compare-box');add(box,'h2','','原始画面中，没有雨伞。');if(state.first&&state.second){const result=C.comparison(state.first,state.second.choice);add(box,'div','record-line','第一次：先看下方封存的文字记录');add(box,'div','record-line','第二次：'+S.memoryOptions[state.second.choice]);add(box,'h3','',result.title);add(box,'p','',result.body);{const detail=add(box,'details');add(detail,'summary','','查看最初自由描述');add(detail,'p','original-text','自由描述：'+(state.first.text||'（未填写）'));add(detail,'p','original-text','补充文字：'+(state.first.other||'（未填写）'));add(detail,'p','small','未提到某物不等于明确否认它存在；提到「伞」字也不等于报告看见。');}}
add(box,'p','small','没有受到影响，也不是失败。这不是对个人记忆能力的测验。');continueButton(wrap,p.button);}
function researchPage(p){const wrap=base(p,true);paragraphs(wrap,p.text);add(wrap,'p','text-lead',p.end);continueButton(wrap,p.button);}
function conceptPage(p){const wrap=base(p,true);p.text.forEach((t,i)=>{const c=add(wrap,'div','concept');add(c,'h2','term',['误导信息效应','记忆的重建','来源监控'][i]);add(c,'p','',t);});add(wrap,'div','feedback',p.end);add(wrap,'p','notice','正式研究应在最后测试前不揭示答案、不进行这些教学提示，并控制其他条件。错误报告本身也不一定意味着记忆痕迹已被改写。');continueButton(wrap,p.button);}
function twistPage(p){const wrap=add(app,'section','reversal');paragraphs(wrap,p.text,'reveal-line');add(wrap,'h1','you',p.end);const title=add(wrap,'div','title-card');add(title,'h2','full-title','记忆里多出来的那把伞');add(title,'p','muted','一次关于记忆、暗示与证据的调查');continueButton(wrap,p.button);}
function scorePage(){const wrap=base(S.pages[15]);const sum=C.summary(state.questions);const grid=add(wrap,'div','score-layout');const score=add(grid,'div','score-card');add(score,'div','','调查记录 / 4:17');const number=add(score,'div','score',String(sum.score));add(number,'span','',' / 100');const metrics=add(score,'div','metrics');[['首次独立答对',sum.independent],['纠错后掌握',sum.corrected],['借助提示掌握',sum.hinted]].forEach(([k,v])=>{const line=add(metrics,'div');add(line,'span','',k);add(line,'strong','',v+' / 5');});add(score,'p','','这份成绩衡量五次推理判断，不评价你的记忆好坏。');const right=add(grid,'div');['记忆不是录像。','后来的信息可能影响回忆。','确信不等于准确。'].forEach((t,i)=>{const d=add(right,'div','takeaway');add(d,'h3','',t);add(d,'p','',S.pages[15].text[i]);});const details=add(wrap,'details','audit');add(details,'summary','','查看五题答题记录');state.questions.forEach((q,i)=>add(details,'div','audit-row',`Q${i+1} · 首答 ${q.first===null?'未答':'ABCD'[q.first]} · 提示 ${q.hint?'使用':'未使用'} · 作答 ${q.attempts.length} 次 · ${q.points??0} 分`));const a=add(wrap,'div','actions');if(state.page===15)button(a,'最后一个问题  →',next);else button(a,'返回反思',()=>{viewResult=false;render();});button(a,'下载调查记录',download,'secondary');}
function reflectionPage(p){const wrap=base(p,true);paragraphs(wrap,p.text);field(wrap,'你的判断（不计分）','写一两句话就好。请勿填写姓名或其他个人信息。',state.reflection,v=>{state.reflection=v;state.reflectionSaved=false;save();const m=document.querySelector('#reflection-status');if(m)m.textContent='草稿已在本机保存';});const actions=add(wrap,'div','actions');button(actions,p.button,()=>{state.reflectionSaved=true;state.completedAt=new Date().toISOString();save();document.querySelector('#reflection-status').textContent=storageOK?'已加入你的调查记录。调查结束。':'已记录在本次会话，请下载保存。';});button(actions,'查看成绩',()=>{viewResult=true;render();},'secondary');button(actions,'下载调查记录',download,'secondary');const status=add(wrap,'p','notice',state.reflectionSaved?'已加入你的调查记录。调查结束。':'文字仅保存在你的浏览器中，不会上传。');status.id='reflection-status';status.setAttribute('role','status');add(wrap,'p','text-lead',p.end);const thanks=add(wrap,'section','credits');add(thanks,'h2','','特别鸣谢');paragraphs(thanks,['特别感谢王智娴、纪嘉怡同学的试玩与反馈，是你们的建议让这次尝试更为有趣且严谨。','特别鸣谢GPT6-Astra为本次工作提供了技术支持（）','也感谢张耀宇老师开源，让我的五小时额度不至于转瞬即逝。']);const credits=add(wrap,'details','credits');add(credits,'summary','','作品说明与研究来源');add(credits,'p','','原创教学故事。情节与插画为虚构；参考《迷雾中的探险》的反馈与计分形式。AI 辅助文案、插画、开发及测试。');[['误导信息效应 · APA','https://dictionary.apa.org/misinformation-effect'],['来源监控 · Johnson 等（1993）','https://pubmed.ncbi.nlm.nih.gov/8346328/'],['参考项目 · 迷雾中的探险','https://github.com/yaoyuzhang1/socrates-question']].forEach(([text,url])=>{const p=add(credits,'p');const a=add(p,'a','',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';});}
function download(){const payload={...state,summary:C.summary(state.questions),note:'个人教学体验记录，不是受控实验数据。自由描述与多选须共同检查。'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=el('a');a.href=url;a.download='4-17-investigation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const dialog=document.querySelector('#restart-dialog');document.querySelector('#restart').onclick=()=>dialog.showModal();document.querySelector('#cancel-restart').onclick=()=>dialog.close();document.querySelector('#confirm-restart').onclick=()=>{clearTimeout(sceneTimer);cancelAnimationFrame(sceneFrame);activeScene=false;try{localStorage.removeItem(C.KEY);}catch(e){}state=C.fresh(true);viewResult=false;selected=null;feedback=null;dialog.close();save();render();};document.querySelector('.brand').onclick=e=>e.preventDefault();
document.addEventListener('visibilitychange',()=>{if(document.hidden&&activeScene)closeScene(true);});window.addEventListener('pagehide',()=>{if(activeScene)closeScene(true);});window.addEventListener('pageshow',e=>{if(e.persisted){try{const saved=JSON.parse(localStorage.getItem(C.KEY));if(C.valid(saved))state=saved;}catch(e){}activeScene=false;render();}});window.addEventListener('popstate',()=>{if(activeScene)closeScene(true);else render();});window.addEventListener('storage',e=>{if(e.key!==C.KEY)return;try{const changed=JSON.parse(e.newValue);if(C.valid(changed)){clearTimeout(sceneTimer);cancelAnimationFrame(sceneFrame);activeScene=false;state=changed;selected=null;feedback=null;viewResult=false;render();}}catch(e){}});render();
})();
