(function(root){
'use strict';
const KEY='memory417.chapter.v2';
function fresh(replay=false){return {version:2,id:Date.now()+'-'+Math.random().toString(36).slice(2),page:0,replay,createdAt:new Date().toISOString(),scene:{started:false,finished:false,interrupted:false},first:null,freeDraft:'',freeLocked:false,firstDraft:[],otherDraft:'',details:null,leading:null,second:null,questions:Array.from({length:5},()=>({first:null,attempts:[],hint:false,solved:false,points:null})),reflection:'',reflectionSaved:false};}
function valid(s){return !!s&&s.version===2&&Number.isInteger(s.page)&&s.page>=0&&s.page<=16&&typeof s.id==='string'&&s.scene&&typeof s.scene.started==='boolean'&&Array.isArray(s.questions)&&s.questions.length===5&&s.questions.every(q=>q&&Array.isArray(q.attempts)&&typeof q.hint==='boolean'&&typeof q.solved==='boolean'&&(q.first===null||[0,1,2,3].includes(q.first))&&(!q.solved||[30,60,100].includes(q.points)))&&(s.first===null||(Array.isArray(s.first.items)&&typeof s.first.text==='string'))&&(s.second===null||[0,1,2,3,4].includes(s.second.choice))&&typeof s.reflection==='string';}
function answer(q,choice,correct){if(q.solved)return q; const n={...q,attempts:[...q.attempts,choice],first:q.first===null?choice:q.first};if(choice===correct){n.solved=true;n.points=n.hint?30:n.attempts.length===1?100:60;}return n;}
function hint(q){return q.solved?q:{...q,hint:true};}
function summary(qs){return {score:Math.round(qs.reduce((n,q)=>n+(q.points||0),0)/5),independent:qs.filter(q=>q.points===100).length,corrected:qs.filter(q=>q.points===60).length,hinted:qs.filter(q=>q.points===30).length};}
function comparison(first,second){const mentioned=/伞/.test((first.text||'')+' '+(first.other||''));const yes=second===0||second===1;if(mentioned)return {kind:'mentioned',title:'先核对你最初写下的原句',body:'你的最初文字中出现了「伞」字。它可能是在说看到了，也可能是在说没有看到或不确定；系统不把提到这个字自动算作看见了伞。请结合下面的原句与第二次回答比较，不能直接把差异归因于后来的描述。'};if(yes)return {kind:'changed',title:'两份记录，出现了差异',body:'最初的自由描述和补充文字没有提到雨伞；听过后来的描述和问题后，你报告可能见过它。没有提到不等于明确记得没有，这次差异也不足以证明原因。要检验后来信息的影响，还需要对照比较。'};if(second===3)return {kind:'uncertain',title:'你保留了不确定',body:'最初的文字没有提到雨伞，第二次你选择无法确定。我们不能把未提及或不确定当成确定没见过，也不能据此判断你是否受到了影响。'};return {kind:'stable',title:'这一次，你没有报告那把伞',body:'最初的文字没有提到雨伞，第二次你报告没有或好像没有。这不代表体验失败，也不能证明这种影响不存在。接下来需要比较不同条件下的结果。'};}
root.MemoryCore={KEY,fresh,valid,answer,hint,summary,comparison};if(typeof module!=='undefined')module.exports=root.MemoryCore;
})(typeof window!=='undefined'?window:globalThis);
