(function(root){
'use strict';
const KEY='memory417.chapter.v1';
function fresh(replay=false){return {version:1,id:Date.now()+'-'+Math.random().toString(36).slice(2),page:0,replay,createdAt:new Date().toISOString(),scene:{started:false,finished:false,interrupted:false},first:null,freeDraft:'',freeLocked:false,firstDraft:[],otherDraft:'',details:null,second:null,questions:Array.from({length:5},()=>({first:null,attempts:[],hint:false,solved:false,points:null})),reflection:'',reflectionSaved:false};}
function valid(s){return !!s&&s.version===1&&Number.isInteger(s.page)&&s.page>=0&&s.page<=16&&typeof s.id==='string'&&s.scene&&typeof s.scene.started==='boolean'&&Array.isArray(s.questions)&&s.questions.length===5&&s.questions.every(q=>q&&Array.isArray(q.attempts)&&typeof q.hint==='boolean'&&typeof q.solved==='boolean'&&(q.first===null||[0,1,2,3].includes(q.first))&&(!q.solved||[30,60,100].includes(q.points)))&&(s.first===null||(Array.isArray(s.first.items)&&typeof s.first.text==='string'))&&(s.second===null||[0,1,2,3,4].includes(s.second.choice))&&typeof s.reflection==='string';}
function answer(q,choice,correct){if(q.solved)return q; const n={...q,attempts:[...q.attempts,choice],first:q.first===null?choice:q.first};if(choice===correct){n.solved=true;n.points=n.hint?30:n.attempts.length===1?100:60;}return n;}
function hint(q){return q.solved?q:{...q,hint:true};}
function summary(qs){return {score:Math.round(qs.reduce((n,q)=>n+(q.points||0),0)/5),independent:qs.filter(q=>q.points===100).length,corrected:qs.filter(q=>q.points===60).length,hinted:qs.filter(q=>q.points===30).length};}
function comparison(first,second){const yes=second===0||second===1;const selected=first.items.includes('雨伞');if(selected)return {kind:'initial',title:'这个线索，比小林来得更早',body:'你在小林说话前就已选择「雨伞」。这可能涉及注意、猜测或选项带来的线索。无论后来怎样回答，都不能把这一次记录直接归因于小林。'};if(yes)return {kind:'changed',title:'两份记录，出现了差异',body:'第一次多选记录中，你没有选择「雨伞」；听过后来的描述和问题后，你报告可能见过它。这提示我们追问信息的来处，但未选择不等于确定没看见，一次变化也不能证明原因。'};if(second===3)return {kind:'uncertain',title:'你保留了不确定',body:'第一次你没有选择「雨伞」，第二次你没有确认有或没有。不能把「不确定」当作确定没见过，也不能据此判断你是否受到了影响。保留判断同样有价值。'};return {kind:'stable',title:'这一次，你没有报告那把伞',body:'第一次你没有选择「雨伞」，第二次你报告没有或好像没有。这不代表体验失败，也不能证明这种影响不存在。要判断是否有系统性的影响，需要比较两组人的结果。'};}
root.MemoryCore={KEY,fresh,valid,answer,hint,summary,comparison};if(typeof module!=='undefined')module.exports=root.MemoryCore;
})(typeof window!=='undefined'?window:globalThis);
