/* Run: npm install --no-save playwright; npx playwright install chromium; node tests/browser.test.cjs */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
let pw;try{pw=require('playwright')}catch{pw=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')}
const C=require('../core.js');const S=require('../content.js');const out=path.join(__dirname,'../docs');const base=process.env.TEST_URL||'http://127.0.0.1:4173';const results=[];
(async()=>{const browser=await pw.chromium.launch(process.env.TEST_CHANNEL?{channel:process.env.TEST_CHANNEL,headless:true}:{headless:true});const ctx=await browser.newContext({viewport:{width:1366,height:900}});const p=await ctx.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));const pass=(name,extra='')=>{results.push({name,status:'PASS',detail:extra});console.log('PASS '+name+' '+extra)};const read=()=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),C.KEY);const button=label=>p.getByRole('button',{name:label,exact:true});const next=()=>button('继续  →').click();const answer=async i=>{await p.locator('input[name="answer"]').nth(i).check();await p.getByRole('button',{name:/^(提交判断|重新提交)$/}).click();};
await p.goto(base);await p.waitForLoadState('networkidle');await p.screenshot({path:path.join(out,'preview-desktop.png'),fullPage:true});assert(!await p.locator('body').innerText().then(t=>t.includes('误导信息效应')||t.includes('记忆里多出来')));pass('开场无标题或术语剧透');
await button('看看发生了什么  →').click();await p.locator('.exposure img').waitFor();const start=Date.now();await p.locator('.exposure img').waitFor({state:'detached',timeout:7000});const elapsed=Date.now()-start;assert(elapsed>=4600&&elapsed<5600,elapsed);pass('首次目击约五秒后自动封存',elapsed+' ms（DOM观测）');await p.reload();assert.equal(await p.locator('.exposure img').count(),0);pass('观看后刷新不能回看');await next();
await p.locator('textarea').fill('我看到倒下的椅子和红色的本子。');await button('保存描述，继续记录').click();await p.getByLabel('倒下的椅子',{exact:true}).check();await p.getByLabel('红色笔记本',{exact:true}).check();await button('保存我的记忆').click();assert.equal((await read()).first.umbrellaSelected,false);await next();
await answer(0);assert.equal((await read()).questions[0].first,0);await p.reload();await answer(2);assert.equal((await read()).questions[0].points,60);await next();pass('错误首答刷新后仍保存，纠错60分');
await button('继续记录  →').click();await button('需要一点提示？').click();await p.reload();await answer(3);assert.equal((await read()).questions[1].points,30);await next();pass('提示状态刷新后保留，答对30分');
await p.getByLabel('红色',{exact:true}).check();await p.getByLabel('桌面上',{exact:true}).check();await button('保存细节').click();await next();await answer(1);await next();await p.getByLabel('好像有',{exact:true}).check();await button('封存这次回答').click();await p.reload();assert.equal(await p.locator('input[name="second"]').count(),0);await button('查看原始记录  →').click();assert(await p.getByText('两份记录，出现了差异',{exact:true}).isVisible());await p.getByRole('button',{name:'✓ 红色笔记本',exact:true}).click();await p.screenshot({path:path.join(out,'preview-reveal.png'),fullPage:true});pass('两次记录独立保存，揭晓正确比较并定位证据');
await button('继续调查  →').click();await answer(1);await next();await button('设计一次实验  →').click();await answer(1);await next();assert(await p.getByRole('heading',{name:'误导信息效应',exact:true}).isVisible());await button('回到故事  →').click();assert.equal(await p.title(),'记忆里多出来的那把伞');await button('查看调查结果  →').click();assert.equal(C.summary((await read()).questions).score,78);assert(await p.locator('.score').innerText().then(t=>t.includes('78')));await p.screenshot({path:path.join(out,'preview-score.png'),fullPage:true});pass('完整17页链条与混合计分78分');
await button('最后一个问题  →').click();await p.locator('textarea').fill('证词可能来自交流，需要独立核验。<script>bad()</script>');await button('保存我的想法').click();await p.reload();assert.equal(await p.locator('textarea').inputValue(),'证词可能来自交流，需要独立核验。<script>bad()</script>');const download= p.waitForEvent('download');await button('下载调查记录').click();await download;pass('反思刷新保存、文本安全和记录下载');
const final=await read();for(const w of [320,390,768]){await p.setViewportSize({width:w,height:844});for(let i=0;i<17;i++){if(i===1)continue;const seed=JSON.parse(JSON.stringify(final));seed.page=i;await p.evaluate(({key,state})=>localStorage.setItem(key,JSON.stringify(state)),{key:C.KEY,state:seed});await p.reload();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`overflow ${w} page ${i}`);if(w===390&&(i===0||i===5))await p.screenshot({path:path.join(out,`preview-mobile-${i}.png`),fullPage:true});}pass('响应式全部常规页面无横向溢出',w+'px');}
await p.evaluate(k=>{localStorage.setItem('unrelated.chapter','keep');localStorage.setItem(k,JSON.stringify({...JSON.parse(localStorage.getItem(k)),page:16}));},C.KEY);await p.reload();await button('重新开始').click();await button('清空本关并重新开始').click();let reset=await read();assert.equal(reset.page,0);assert.equal(reset.first,null);assert.equal(reset.second,null);assert(reset.questions.every(q=>q.first===null));assert.equal(await p.evaluate(()=>localStorage.getItem('unrelated.chapter')),'keep');assert(reset.replay);pass('重新开始只清本关，标记重玩');
await button('看看发生了什么  →').click();await p.locator('.exposure img').waitFor();await p.reload();assert.equal(await p.locator('.exposure img').count(),0);assert((await read()).scene.interrupted);pass('目击中刷新立即封存，不能重新计时');await p.goto(base+'/?away=1');await p.goBack();assert.equal(await p.locator('.exposure img').count(),0);pass('浏览器返回不能解锁目击画面');
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError')}});const bp=await blocked.newPage();await bp.goto(base);await bp.getByRole('button',{name:'看看发生了什么  →',exact:true}).click();await bp.locator('.exposure img').waitFor();assert(await bp.locator('#storage-warning').isVisible());await blocked.close();pass('localStorage不可写时显示警告且可继续');
const missing=await browser.newContext();const mp=await missing.newPage();await mp.route('**/assets/scene.png',r=>r.abort());await mp.goto(base);await mp.getByRole('button',{name:'看看发生了什么  →',exact:true}).click();await mp.getByRole('button',{name:'重新载入画面'}).waitFor();assert.equal(await mp.locator('.exposure img').count(),0);await missing.close();pass('图片加载失败不启动五秒计时');
const local=await browser.newContext();const lp=await local.newPage();await lp.goto('file:///'+path.resolve(__dirname,'../index.html').replace(/\\/g,'/'));assert(await lp.getByRole('button',{name:'看看发生了什么  →',exact:true}).isVisible());await local.close();pass('直接打开本地HTML可运行');assert.equal(errors.length,0);pass('全程无JavaScript运行错误');
fs.writeFileSync(path.join(out,'browser-test-results.json'),JSON.stringify({at:new Date().toISOString(),browser:'Chromium / '+(process.env.TEST_CHANNEL||'bundled'),results,errors},null,2));await browser.close();console.log(`${results.length} browser checks passed`);
})().catch(e=>{console.error(e);process.exit(1)});
